### PR TITLE
Header body

### PR DESCRIPTION
**Pull request by Fx-Colliot**

### CODE REVIEW

**Review by Thoms-C — CHANGES_REQUESTED** [review]
you need to change the vh into rem for the font-size (HeaderBodyStyled.jsx)

**Review by Thoms-C — DISMISSED** [review]
Seems ok for me, but be careful with comits name (2 prettify in a row)

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by Thoms-C — APPROVED** [review]
Clear!

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
