### PR TITLE
Document

### PR DESCRIPTION
**Pull request by Gauthier-Lhomme**
Page documentation

### CODE REVIEW

**Review by Marie-Garde — DISMISSED** [review]
Nickel to me !

**Review by Thoms-C — DISMISSED** [review]
Seem ok to me !

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by Marie-Garde — APPROVED** [review]
Ok !

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
