### PR TITLE
Header top

### PR DESCRIPTION
**Pull request by Fx-Colliot**

### CODE REVIEW

**Review by Thoms-C — DISMISSED** [review]
Seems ok for me, but you need to name the last commit 'Prettify'

**Comment by LoicBrassart** [comment]
> Seems ok for me, but you need to name the last commit 'Prettify'

So it's not OK, it misses the code "prettification" ;-)

**Comment by Fx-Colliot** [comment]
Good, last commit is "prettify"

**Review by Thoms-C — DISMISSED** [review]
OK for me !

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by Thoms-C — APPROVED** [review]
Ok !

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
